site_name: AkStudy
site_description: 'A place to learn all the stuff.'
site_author: 'Alukos'
docs_dir: docs/
repo_name: 'xyelz/study'
repo_url: 'https://github.com/xyelz/study'
nav:
  - Home: index.md
theme:
  favicon: assets/images/favicon.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.top
  logo: assets/images/logo.svg
  name: 'material'
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
extra:
  generator: false
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.alukos.com
      name: Alukos on Discord
