name: Build & Deploy to Cloudflare Worker

on:
  push:
    branches:
      - main
  repository_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build & Deploy
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
      - name: Deploy docs & publish site
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{secrets.CF_API_TOKEN}}
          wranglerVersion: '1.13.0'
        env:
          CF_ACCOUNT_ID: ${{secrets.CF_ACCOUNT_ID}}
          CF_ZONE_ID: ${{secrets.CF_ZONE_ID}}
          USER: root
          CONFIG_FILE: folder/mkdocs.yml
          EXTRA_PACKAGES: build-base
